[workspace]
allow_dirty = false
changelog_update = true
dependencies_update = false
publish_allow_dirty = false
# feature auto detection is no longer compatible with the k8s-openapi feature approach
semver_check = false
